package remote

import (
	"crypto/subtle"
	"encoding/base64"
	"net/http"
	"strings"
)

const websocketAccessProtocolPrefix = "vulpine-key."

// Authenticator validates incoming connections.
type Authenticator struct {
	apiKey string
}

// NewAuthenticator creates an authenticator with the given API key.
func NewAuthenticator(apiKey string) *Authenticator {
	return &Authenticator{apiKey: apiKey}
}

// Validate checks the request for a valid API key.
// Accepts: Authorization: Bearer <key> header, ?token=<key> query param, or
// a websocket access subprotocol generated by PanelAccessSubprotocol.
func (a *Authenticator) Validate(r *http.Request) bool {
	if a.apiKey == "" {
		return true // no auth configured
	}

	// Check Authorization header
	auth := r.Header.Get("Authorization")
	if len(auth) > 7 && auth[:7] == "Bearer " {
		token := auth[7:]
		if subtle.ConstantTimeCompare([]byte(token), []byte(a.apiKey)) == 1 {
			return true
		}
	}

	// Check query parameter
	token := r.URL.Query().Get("token")
	if token != "" && subtle.ConstantTimeCompare([]byte(token), []byte(a.apiKey)) == 1 {
		return true
	}

	if a.AcceptedWebSocketSubprotocol(r) != "" {
		return true
	}

	return false
}

// PanelAccessSubprotocol encodes a panel access key as an RFC6455-compatible
// websocket subprotocol token, keeping the key out of the websocket URL.
func PanelAccessSubprotocol(apiKey string) string {
	if apiKey == "" {
		return ""
	}
	return websocketAccessProtocolPrefix + base64.RawURLEncoding.EncodeToString([]byte(apiKey))
}

// AcceptedWebSocketSubprotocol returns the matching access subprotocol, if any.
func (a *Authenticator) AcceptedWebSocketSubprotocol(r *http.Request) string {
	if a.apiKey == "" || r == nil {
		return ""
	}
	for _, header := range r.Header.Values("Sec-WebSocket-Protocol") {
		for _, raw := range strings.Split(header, ",") {
			protocol := strings.TrimSpace(raw)
			if protocol == "" || !strings.HasPrefix(protocol, websocketAccessProtocolPrefix) {
				continue
			}
			encoded := strings.TrimPrefix(protocol, websocketAccessProtocolPrefix)
			token, err := base64.RawURLEncoding.DecodeString(encoded)
			if err != nil {
				continue
			}
			if subtle.ConstantTimeCompare(token, []byte(a.apiKey)) == 1 {
				return protocol
			}
		}
	}
	return ""
}
